-- pvzol_local MySQL schema (minimal)
-- Database: pvzol_root

CREATE TABLE IF NOT EXISTS players (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  seed VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_players_seed (seed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kv (
  k VARCHAR(191) NOT NULL,
  v MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (k)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS player_state (
  user_id BIGINT PRIMARY KEY,
  phase VARCHAR(64) NOT NULL,
  state_json JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inventory (
  user_id BIGINT NOT NULL,
  item_id VARCHAR(64) NOT NULL,
  qty BIGINT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS shop_orders (
  order_key VARCHAR(128) NOT NULL,
  user_id BIGINT NOT NULL,
  api_name VARCHAR(64) NOT NULL,
  request_json JSON NOT NULL,
  response_json JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (order_key),
  KEY idx_shop_orders_user_api (user_id, api_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sig_user (
  sig VARCHAR(128) NOT NULL,
  user_id BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (sig),
  UNIQUE KEY uniq_sig_user_user_id (user_id),
  KEY idx_sig_user_last_seen (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS auth_tokens (
  token_hash CHAR(64) NOT NULL,
  user_id BIGINT NOT NULL,
  issued_at DATETIME NOT NULL,
  expires_at DATETIME NOT NULL,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (token_hash),
  KEY idx_auth_tokens_user_id (user_id),
  KEY idx_auth_tokens_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS replay_guard (
  replay_key VARCHAR(191) NOT NULL,
  user_id BIGINT NOT NULL,
  api_name VARCHAR(64) NOT NULL,
  response_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  PRIMARY KEY (replay_key),
  KEY idx_replay_guard_api_exp (api_name, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS organisms (
  org_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  tpl_id INT NOT NULL,
  level INT NOT NULL DEFAULT 1,
  quality INT NOT NULL DEFAULT 1,
  exp BIGINT NOT NULL DEFAULT 0,
  hp BIGINT NOT NULL DEFAULT 100,
  hp_max BIGINT NOT NULL DEFAULT 100,
  attack BIGINT NOT NULL DEFAULT 100,
  miss BIGINT NOT NULL DEFAULT 0,
  speed BIGINT NOT NULL DEFAULT 50,
  precision_val BIGINT NOT NULL DEFAULT 0,
  new_miss BIGINT NOT NULL DEFAULT 0,
  new_precision BIGINT NOT NULL DEFAULT 0,
  quality_name VARCHAR(32) NOT NULL DEFAULT '普通',
  dq INT NOT NULL DEFAULT 0,
  gi INT NOT NULL DEFAULT 0,
  mature INT NOT NULL DEFAULT 1,
  ss BIGINT NOT NULL DEFAULT 0,
  sh BIGINT NOT NULL DEFAULT 0,
  sa BIGINT NOT NULL DEFAULT 0,
  spr BIGINT NOT NULL DEFAULT 0,
  sm BIGINT NOT NULL DEFAULT 0,
  new_syn_precision BIGINT NOT NULL DEFAULT 0,
  new_syn_miss BIGINT NOT NULL DEFAULT 0,
  fight BIGINT NOT NULL DEFAULT 0,
  skill VARCHAR(255) NOT NULL DEFAULT '',
  exskill VARCHAR(255) NOT NULL DEFAULT '',
  tal_add_xml TEXT NULL,
  soul_add_xml TEXT NULL,
  tals_xml TEXT NULL,
  soul_value INT NOT NULL DEFAULT 0,
  skills_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (org_id),
  KEY idx_organisms_user (user_id),
  KEY idx_organisms_user_org (user_id, org_id),
  KEY idx_organisms_user_tpl (user_id, tpl_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS currency_spend_stat (
  user_id BIGINT NOT NULL,
  currency VARCHAR(32) NOT NULL,
  total_spent BIGINT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, currency)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
